version: '3.8'

services:
  # db:
  #   container_name: db
  #   image: postgres:latest
  #   volumes:
  #     - db_volume:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '5432:5432'

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '14000:6379'
    volumes:
    - redis_volume:/data

  # backend:
  #   container_name: back
  #   build: ../src/
  #   image: 
  #   restart: always
  #   depends_on:
  #     - db
  #   volumes:
  #     - static_volume:/app/static/
  #     - media_volume:/app/media/
  #   env_file:
  #     - ./.env

  # nginx:
  #   container_name: nginx
  #   image: nginx:1.21.3-alpine
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - static_volume:/var/html/static/
  #     - media_volume:/var/html/media/
  #   depends_on:
  #     - backend
  

volumes:
  db_volume:
  static_volume:
  media_volume:
  redis_volume: