"""initial

Revision ID: 68ec7a56bf72
Revises: 
Create Date: 2023-05-02 16:15:02.485664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68ec7a56bf72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
